# this is an example configuration file for nvrs
# https://github.com/adamperkowski/nvrs

[__config__]
oldver = "oldver.json"
newver = "newver.json"
keyfile = "n_keyfile.toml"

[julec]
source = "github"
github = "julelang/jule"
prefix = "jule"

[comlink]
source = "aur"
aur = "comlink"

[mkinitcpio]
source = "gitlab"
host = "gitlab.archlinux.org"
gitlab = "archlinux/mkinitcpio/mkinitcpio"
prefix = "v"

[rustup]
source = "github"
github = "rust-lang/rustup"
use_max_tag = true

[rustrover]
source = 'regex'
url = 'https://data.services.jetbrains.com/products?code=RR&release.type=release'
encoding = 'utf8'
regex = 'RustRover-([\d.]+).tar.gz'

[linux]
source = 'regex'
url = 'https://www.kernel.org/'
encoding = 'utf8'
regex = '<td><strong>([\d.]+)</strong></td>'

[nvrs]
source = "cratesio"
cratesio = "nvrs"

[libkeccak]
source = "gitea"
host = "codeberg.org"
gitea = "maandree/libkeccak"
use_max_tag = true

[kernel]
source = "shell"
shell = "uname -r | cut -d'-' -f1"
