name: Feature Request
description: Request a new feature for nvrs.
labels: [ 'enhancement' ]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand your feature request.

  - type: textarea
    id: feature_summary
    attributes:
      label: Feature Summary
      description: Provide a short summary of the feature.
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case for this feature.
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other context or information about the feature request.
      required: false
